### ISSUE TITLE
Table list behavior

### ISSUE THREAD

**Issue by BogdanScherban** [PulseTile/PulseTile-RA#14]
Behavior of table list should be similar to Showcase:
http://showcase2.ripple.foundation/#/patients/9999999061/allergies/

1) Click on row opens Details block in right of Table;
2) Click on Edit opens Edit form instead of Details block;
3) Click on Cancel returns to Details block;
4) Click on Create open Create form instead of Details block.

**Comment by BogdanScherban** [comment]
@tony-shannon @fzaninotto 

I realized this behavior in RA (for Allergies). Results on the video:
https://drive.google.com/file/d/1-2oZvZS0Iq9Heao2c-PeDZGeye6BntYy/view?usp=sharing

But I need in @fzaninotto advice:

1) I didn't find a way how to customize following elements: **SaveButton**, **ListButton** and **Pagination**.  

In first two cases I want to rename buttons and change them icons.
In the last one I want to leave only buttons with digits and remove all other elements. I can do this by CSS, but is other way presented?

2) Can we set date format in **DisabledField** form element? 
Server returns date in timestamp. **DateField** converts it to date automatically, but **DisabledField** output it as a string.

3) All custom styles, which I added to List, Create / Edit form, Expansion Panels etc. will be presented in all our resources (I mean Contacts, Vaccinations, Medications etc.)
Does it make sense to locate these styles in separate file (outside the components), and import it?
In opposite case we should copy them in 6 places (as minimal).

I saved my results to my GitHub branch:
https://github.com/BogdanScherban/PulseTile-RA/tree/page-behavior

**Comment by fzaninotto** [comment]
Here are my answers:

1. All action buttons accept a `label` and an `icon` prop since react 2.5.0. So it should be straightforward. As for the pagination, the Pagination component doesn't offer the ability to hide arrow buttons, so you'll have to write your own Pagination component from scratch. But maybe it's better to show them, @tony-shannon ?
2. Try using a `<DateField disabled />`
3. Instead, create components with those styles, and reuse the components rather than the styles

**Comment by tony-shannon** [comment]
> 1. As for the pagination, the Pagination component doesn't offer the ability to hide arrow buttons, so you'll have to write your own Pagination component from scratch. But maybe it's better to show them, @tony-shannon ?

I see no issue with leaving the arrow buttons , so show them please

**Comment by BogdanScherban** [comment]
@fzaninotto 

Thanks, Francois! 

I've already customize List and Save buttons and added <DateField disabled />. 
Now I'm working on common components for Edit/Create/Show/List (item 3).

On Monday I hope finish this issue and  create PR for it.

**Comment by BogdanScherban** [comment]
Pull request for this issue:
https://github.com/PulseTile/PulseTile-RA/pull/16
