### ISSUE TITLE
List filter

### ISSUE THREAD

**Issue by BogdanScherban** [PulseTile/PulseTile-RA#15]
@fzaninotto 

Francois, I need in your advice in this issue.

I tried to add filter to our **List**. But this filter should be differ on initial React-admin filter. It should be similar to Showcase filter. It work principle is shown at the video:
https://drive.google.com/file/d/10yAt_ZtPf-Ljw49RP1ZCMzZI5N1yterX/view?usp=sharing

My solution looks approximately like this:

```
class MyList extendes Component {
  
  state = {
     search: null,
  }

  setMySearch = e => {
      this.setState({
         search: e.target.value,   
      })
  }

  render() {
    const { search } = this.state; 
    return (
      <ListBlock>
         <MyFilter onChange={e => this.setMySearch(e)} />
         <List>
            <MyCustomDatagrid mySearch={search} />
         </List>
      </ListBlock>
    );
  }
}

```

In **MyCustomDatagrid** I want to catch changing of **search** by componentWillReceiveProps():

```
class MyCustomDatagrid extends Component {
   
  componentWillReceiveProps(newProps) {
    ......
  }

  render() {
     ....
  }
}
```

But component MyCustomDatagrid isn't re-rendered, when I change **search**.
The reason is - MyCustomDatagrid is located inside RA **List**. I tried to extract MyCustomDatagrid from List and re-render works!

My solution is located here:
https://github.com/BogdanScherban/PulseTile-RA/blob/filter-try/src/core/plugins/Allergies/AllergiesList.js

Could you please tell me how can I realize this type of filter?

**Comment by BogdanScherban** [comment]
Thanks, @fzaninotto ! It works!!!

**Comment by BogdanScherban** [comment]
@tony-shannon @fzaninotto 
I created PR for this issue:
https://github.com/PulseTile/PulseTile-RA/pull/17

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett can we consider this as Done?
