### ISSUE TITLE
Add Contrast Mode

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-RA#18]
We should add Contrast Mode for RA, as we have in Helm and by clicking on it the app became bw: https://www.screencast.com/t/OqhCxPDg

Approx. estimate time: 4-5h

**Comment by BogdanScherban** [comment]
@fzaninotto 

Francois, could you please give me advice according to this issue?

Contrast mode should be tobble by the button in Topbar like it was at ReactJS Helm version:
https://drive.google.com/file/d/19sZObYslDJb2MASCBEEY1Wvjy66PU7yO/view?usp=sharing

I created actions, reducer and sagas which provide toggling of contrast mode parameter in Store.

But I don't know, how to provide changing of color in theme settings?

we set main theme color in theme settings:

```
export const MAIN_THEME_COLOR = "#3596f4";
```

and import it in theme creation: 

```
import { MAIN_THEME_COLOR }  from "../../version/config/theme.config";

export const currentTheme = createMuiTheme({
...
     mySelector: {
           myProperty: MAIN_THEME_COLOR
     }
...
})
```

But have we any way to define MAIN_THEME_COLOR constant depends on store parameter "isContrastMode"?

**Comment by BogdanScherban** [comment]
@fzaninotto 
Thanks, Francois! It works!!!

**Comment by PhilBarrett** [comment]
Looks good. @kuvakina if replicating behaviour in React version, I believe you can toggle in via the footer as well.

**Comment by kuvakina** [comment]
We added it in this issue: https://waffle.io/RippleOSI/combined-development-view/cards/5c518734851b7604e99c567b

**Comment by PhilBarrett** [comment]
Checked and linked with https://waffle.io/RippleOSI/combined-development-view/cards/5c5177f1085f6a0563ddf557 which is complete so closing
