### ISSUE TITLE
Add High Contrast mode in Footer

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-RA#21]
Add Fotter to RA as in Helm, with contrast mode: https://www.screencast.com/t/iSudf61sx3

Approx estimate time: 4h

**Comment by PhilBarrett** [comment]
@BogdanScherban can you reference the PR please so we can close off

**Comment by PhilBarrett** [comment]
Linked to issue https://waffle.io/RippleOSI/combined-development-view/cards/5c5177f1085f6a0563ddf557

**Comment by kuvakina** [comment]
@PhilBarrett so could we also close this issue?
