### ISSUE TITLE
Add Advanced Search to Top Bar.

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-RA#22]
Like in Showcase we have Top bar with advanced search: https://www.screencast.com/t/gTEzvPp1uVC

Approx. estimate time: 6-8h

**Comment by PhilBarrett** [comment]
http://docs.pulsetile.com/react-search.html

**Comment by tony-shannon** [comment]
search is available by surname or ID
need to extend the API to enable further searches

@BogdanScherban to update

**Comment by tony-shannon** [comment]
linked to #29

**Comment by BogdanScherban** [comment]
Client side of this issue was done. But now we can search patients by lastName and by patientId:
https://drive.google.com/file/d/1kcseeS_0xizc5-1iIkXr5xQs7iIbwepg/view

PatientID has more priority than lastname.

All other fields aren't used in search, because we don't have API-method for this.

**Comment by tony-shannon** [comment]
dependent on FHIR searching for work by Dima

**Comment by kuvakina** [comment]
@PhilBarrett @tony-shannon 
Dima working on this issue at the moment

**Comment by PhilBarrett** [comment]
PR being reviewed by Alexey

https://github.com/QEWD-Courier/fhir-mpi/pull/1
