### ISSUE TITLE
Sidebar menu changes

### ISSUE THREAD

**Issue by BogdanScherban** [PulseTile/PulseTile-RA#29]
1) On Charts and Patients pages menu consists of two items: Charts and Patients
2) On Patient Summary and plugins pages: Charts and Patients should be hidden

**Comment by BogdanScherban** [comment]
The issue has been done. PR is ready to review.

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett this issue is done. Can we close it?

**Comment by BogdanScherban** [comment]
@kuvakina 
No yet, because it hasn't been reviewed by Francois.

**Comment by kuvakina** [comment]
ok, @BogdanScherban thank you. Then will wait for A review from @fzaninotto

**Comment by kuvakina** [comment]
This issue is Done, @tony-shannon @PhilBarrett could you review please?

**Comment by PhilBarrett** [comment]
@kuvakina can you ensure the PR and testing is completed and referenced before we close this please.

**Comment by BogdanScherban** [comment]
PR was approved by Francois and merged to develop.
