### ISSUE TITLE
Login via OpenID

### ISSUE THREAD

**Issue by BogdanScherban** [PulseTile/PulseTile-RA#33]
@fzaninotto @tony-shannon 

Login to RA should be done via Open ID service. I tried to solve this issue by two ways, but I'm not satisfied of both results.

Francois, we need in your advice how to realize following login principle (if it can be done generally): 

1) User want to pass to our project by any URL (for example, {domain name}/#/{start page}
2) RA run a request **/api/initialise** to the server path
3) Server return the next result types:
- for authorized user (**token** (new), .....);
- for non-authorized user (**token** (old), **redirectURL**, ....), where redirect URL is redirection to OpenID login page
4) RA should redirect user to OpenID (for non-authorized) or allow him go to RA-pages (authorized). 
________________________________________________________________________________

**My solution 1 (works, but has a lot of disadvantages):**

1) Remove **authProvider** attribute from **Admin** tag.
2) Change **dashboard** to **InitializePage**.
3) Initialize page principle:

```
class InitialisePage extends Component {

    componentDidMount() {
        // This function run /api/initialise request 
        this.props.getCurrentUser();
    }

  render() {
        const { auth } = this.props;  // Results of /api/initialize request from server
        const redirectUrl = get(auth, 'redirectURL', null);  // Redirect to Open ID
        if (redirectUrl) {
            window.location.href = redirectUrl;
        } else if (auth !== null) {
            history.push("/charts");
        }
        return null;
    }

```
**Disadvantages:** 
1) user can see "/charts" page before user will be redirected to OpenID page
2) I should add error handler with message about non-valid token (to each page)

**Solution 2 (don't work generally):**

I tried to add /api/initialize request to root App component:
````
class App extends Component {

    componentDidMount() {
        // This function run /api/initialise request 
        this.props.getCurrentUser();
    }

  render() {
        .......
        .......
        if (redirectUrl) {
             window.location.href = redirectUrl;
        } else {
             return (
                     <Admin></Admin>
             );
        }
  }
}
````

In this case it doesn't work generally, because we don't have actions/reducers/sagas at this stage...

Could you please give me advice according to this issue?
Probably, RA has something like custom HOCs for this issue?

**Comment by fzaninotto** [comment]
Neither of the two solutions you propose follow the react-admin way, which uses Redux actions and the authProvider. Here is what I suggest.

If the user opens any page of the app, the app will call the API without credentials. The API should return something like a 401 or 403. This kind of HTTP error can be caught by the authProvider (see https://marmelab.com/react-admin/Authentication.html#catching-authentication-errors-on-the-api) to redirect the user to the `/login` route.

React-admin lets you customize the component the app displays on the `/login` route (by default, it's react-admin's `Login` component). See https://marmelab.com/react-admin/Authentication.html#customizing-the-login-and-logout-components for details about that.

You'll have to create your own Login component. This component can check if the URL has query parameters.

- if it hasn't any query parameter,  redirect  the user to the OpenId service url. On successful login, the OpenId service should redirect the user to the `/login` url again, this time with a token as a query parameter
- if the url has query parameters, your `Login` component can then dispatch the `userLogin` action with the token, and redirect to the dashboard 

The authProvider catches the `userLogin` action and stores the token in localStorage.

The dataProvider should use this token to authenticate all requests to the API.

Every step of this process is explained in detail in the react-admin documentation:

https://marmelab.com/react-admin/Authentication.html

I invite you to start by reading this chapter.

**Comment by BogdanScherban** [comment]
@fzaninotto 
Thanks, Francois. I was sure that React-Admin can do this by initial functionality.

**Comment by tony-shannon** [comment]
I've asked Rob Tweed who developed our middle tier Qewd-Courier to comment on this;

> Well as I've said before, the best approach is to examine the requests and responses between current PulseTile and the QEWD middle tier - it's all around the /api/initialise which basically returns one of two responses - either a redirect URL or an object that confirms the user is already authenticated - that's pretty much it
> and if the user is authenticated, it also returns a JWT which needs to be saved somewhere safely, and returned with the next request(s)

**Comment by BogdanScherban** [comment]
@fzaninotto @tony-shannon 

Francois, I read the manual and tried to do this. But unfortunately, I didn't reach required result...
Could you please show my solution.

What should we do:
1) Run api/initialise;
2) Take redirect URL to open ID
3) Input login and password
4) Redirect to RA
5) Run /api/initialise until we have response { status: 'loading_data', new_patient: true/false }
6) When response of /api/initialise will be  { ok: true, mode: 'secure' }, we should stop running of /api/initialise
7) Run /api/user and get user information
8) Add user Id, name and role to the localStorage
9) Come to homepage

I tried to solve this issue by two ways. First way gives possibility to pass 8 items, but I can't make the last stage

```
<Admin loginPage={InitializePage}> 
```

Where InitializePage is:
```
import React, { Component } from "react";
...
import { userLogin } from 'react-admin';
import { initializeAction } from "../actions/initializeAction";
import { userInfoAction } from "../actions/userInfoAction";
...
class InitializePage extends Component {

    componentDidMount() {
        // Here I run /api/initialize in the first time, to take redirectURL
        // Redirect - in the Sagas of /api/initialize
        this.props.initializeUser();
    }

    componentWillReceiveProps(newProps) {
        const { userInfo, initialize } = newProps;

        // Here I run /api/initialize until my result is  'loading_data'
        if (get(initialize, 'status', null) === 'loading_data') {
            const isNewPatient = get(initialize, 'new_patient', false);
            setInterval(this.props.initializeUser(), isNewPatient ? 5000 : 1000);

       // Here I run /api/user to get user info
       //  Id, name and role are saved to localStorage in Sagas for /api/user 
        } else if (get(newProps, 'initialize.ok', false) && !userInfo) {
            this.props.getUserInfo();
        }

        // Here I try to dispatch authProvider, and set Promise.resolve(), 
        // if userID and token are presented
        if (userInfo) {
            this.props.userLogin();
        }
    }

    render() {
        return (
            <h1>Loading...</h1> // Place for the loader
        )
    }
}

const mapStateToProps = state => {
    return {
        userInfo: state.custom.userInfo.data,
        initialize: state.custom.initialize.data,
    };
};

const mapDispatchToProps = dispatch => {
    return {
        initializeUser() {
            dispatch(initializeAction.request());
        },
        getUserInfo() {
            dispatch(userInfoAction.request());
        },
        userLogin,
    };
};

export default connect(mapStateToProps, mapDispatchToProps)(InitializePage);
```

I try different methods to dispatch userLogin, but in each case it doesn't work - I can't pass to authProvider.

**Comment by BogdanScherban** [comment]
The second way isn't liked for me, but I describe it:
```
<Admin loginPage={InitializePage}> 
```
InitializePage:
```
import React, { Component } from "react";
import { initializeAction } from "../actions/initializeAction";
...
class InitializePage extends Component {

    componentDidMount() {
        // Here I run /api/initialize in the first time, to take redirectURL
        // Redirect - in the Sagas of /api/initialize
        this.props.initializeUser();
    }
   
    render() {
        return (
            <h1>Loading...</h1> // Place for the loader
        )
    }
}

const mapStateToProps = state => {
    return {
        initialize: state.custom.initialize.data,
    };
};

const mapDispatchToProps = dispatch => {
    return {
        initializeUser() {
            dispatch(initializeAction.request());
        },
    };
};

export default connect(mapStateToProps, mapDispatchToProps)(InitializePage);
```

And authProvider:
```
export default async (type, params) => {
....
    if (type === AUTH_CHECK) {
          // UserId and token are presented
          if (localStorage.getItem('userId') && token) {
                 return Promise.resolve();
          }
          // Only token (from OpenID) 
          else if (token) {
               const initializeResult = await initialize();
               const userInfo = await userInfo();
               if (userInfo) {
                     // Save data to localStorage
                     ...
                     return Promise.resolve();
               } 
          }

          return Promise.reject();
    }
)
```

But in this case we have a lot of problem with async functions, like:
```
function initialize() {
    ....
    ...
    return fetch(url, options).then(res => res.json())
        .then(response => {
            ....
            if (status === 'loading_data') {
                i = setInterval(async () => {
                    await initialize().then(res => {
                        if (res.ok && res.mode === 'secure') {
                            clearInterval(i);
                        }
                    });
                }, isNewPatient ? 5000 : 1000);
            } else if (mode === 'secure' && isDataLoaded) {
                return response;
            }
        });
}
```

**Comment by fzaninotto** [comment]
```
const FetchLogin = (resolve, reject) => fetch(url, options)
    .then(res => res.json())
    .then(response => {
        if (status !== 'loading_data') {
            return resolve(true)
        }
        setTimeOut(() => fetchLogin(callback, reject), 5000);
    });

const initialize = () => new Promise((resolve, reject) => FetchLogin(resolve, reject))
```

**Comment by tony-shannon** [comment]
@fzaninotto looks like your help/tips/advice have helped !
@BogdanScherban has hooked login via openID into App
more work to do Monday but important progress, thanks!

**Comment by BogdanScherban** [comment]
@fzaninotto 

Hi, Francois! Last Friday I realized method 1 with userLogin() inside InitialPage component and it works correctly.

Today I'm trying to realize method 2 (with initialization inside authorization provider) according to your example. But, unfortunately I can't make promises works as it is necessary...

When I use like this one, /api/initialize request run only one time, and we don't pass inside .then(response => ...):
```
const initialize = () => new Promise((resolve, reject) => FetchLogin(resolve, reject))
```

For this reason I changed to: 
```
const initialize = new Promise((resolve, reject) => FetchLogin(resolve, reject))
```

But in this case error occurs when I want to resolve the Promise:
```
const FetchLogin = (resolve, reject) => fetch(url, options)
    .then(res => res.json())
    .then(response => {
        if (get(response, 'status', null) !== 'loading_data') {
            return resolve(true);    // Error like "Uncaught (in promise) TypeError: t is not a function"
        }
        const isNewPatient = get(response, 'new_patient', false);
        const delay = isNewPatient ? NEW_PATIENT_DELAY : OLD_PATIENT_DELAY;
        setTimeout((resolve, reject) => FetchLogin(resolve, reject), delay);
    });
```
Probably, **resolve** is out of scope in fetch().then(). 
For this reason I tried to use:
```
return Promise.resolve(true);
```
or 
```
return;
```

The last variant gives possibility to stop /api/initialise requests after condition.

But I can't pass to .then() after my Promise:
```
            const initialize = new Promise((resolve, reject) => FetchLogin(resolve, reject))
                .then(res => {
                    console.log('***********************************');
                });
```

I save my solution here. Could you please tell me where I do mistake?
https://github.com/BogdanScherban/PulseTile-RA/tree/login-in-provider

**Comment by PhilBarrett** [comment]
@BogdanScherban can you confirm this is now working please?

**Comment by BogdanScherban** [comment]
This issue has been done. PR was approved by Francois and merged to develop.
