### ISSUE TITLE
Apple-cake functionality issues

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-RA#56]
Below I added functional issues (and I'll update it more):

| Functionality | Styles | Status | Comment | Details |
| --------  | -------- | --------  | ------------- | --- |
| SignIn/LogIn with email and password |   |  working  |   | User can login successfully by using their email and password |
| SignIn/LogIn - confirmation sms |    | absent |   | After user fill in their email and password he had to enter code from sms to login |
| Contacts: create contact  |    | to do |   | User can successfully create the contacts |
| Contacts: can’t delete Relationship type: https://www.screencast.com/t/TSG5kLFfnc |    |    | Should this be fixed? | User can't clear/delete contacts. Is it should be this way? |
| SignOut/Logout |    | absent  |   | User can log out from the app by clicking LogOut button |
| Tour |    | working |   | 1) go on Home page and see active pink dot by clicking on "?" button from NOT Home page; 2) run it by clicking on "?" button |

**Comment by PhilBarrett** [comment]
Can you add some more background detail please and link with t https://waffle.io/RippleOSI/combined-development-view/cards/5c791211396b6602620eb51b

**Comment by kuvakina** [comment]
This issue linked to the issue https://github.com/LeedsCC/Helm-PHR-Project/issues/105

**Comment by PhilBarrett** [comment]
We are now using Apple-Cake to test the old version of PulseTile React for Helm only.

**Comment by PhilBarrett** [comment]
@kuvakina can you update here please, is further work required on this?

**Comment by kuvakina** [comment]
@PhilBarrett tested it briefly, everything working except for logout: https://www.screencast.com/t/am9rjYwvRr and shows this error: https://www.screencast.com/t/C7TxvNLdo when click a second time on UserName: https://www.screencast.com/t/qTLORX8tG1cL

**Comment by tony-shannon** [comment]
very helpful thanks @kuvakina 

can we please confirm the version of React/React Admin on this box please.
My info is it is  PulseTile React

**Comment by tony-shannon** [comment]
see updated tests here; 
https://docs.google.com/spreadsheets/d/18VNGRjsZYmp-MnuyMBt4WjMmAQ6H7Wp2En5ePPULygc/edit?usp=sharing
NB Apple Cake now got earlier version of PulseTile React on afaik, to be confirm

**Comment by PhilBarrett** [comment]
@tony-shannon please can you provide a comment on outstanding asks re documentation

**Comment by tony-shannon** [comment]
before we close this can we please ask @BogdanScherban  to write up :
how to set up Pulse React from scratch, ie Core + Plugins + Theme + Generator to build for project (eg Helm) file

**Comment by BogdanScherban** [comment]
@tony-shannon 

If we want to create Helm version on ReactJS, we should  use this npm module:
https://www.npmjs.com/package/generator-helm-phr

This is Generator, which based on Yeoman technology. Generator has detailed description. If you want to use it, you should do following:
1) Check, that versions of node, npm and git at your local machine correspond do required;
2) Install all required dependencies
3) Run sub-generators one-after-other in the order from description.

In this case Helm on ReactJS will be created automatically.

**Comment by tony-shannon** [comment]
thanks @BogdanScherban  and the output from this is the build file?

**Comment by PhilBarrett** [comment]
Please can you add the build file to this path or related
https://github.com/PulseTile/PulseTile-React-Core/tree/master/build

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett could we close this issue, as we don't have Apple-cake server right now?
