### ISSUE TITLE
ReSPECT-plugin (section 7)

### ISSUE THREAD

**Issue by BogdanScherban** [PulseTile/PulseTile-RA#59]
Hi, @fzaninotto 
Francois, could you please give me advice about this issue?

I want to create form with this element:
![0000001](https://user-images.githubusercontent.com/39263134/53738666-7f1bf300-3e98-11e9-9c77-c18b3e4f55ae.png)

We can fill all fields, click on Add New, and new row will be occurred in the table:
![image](https://user-images.githubusercontent.com/39263134/53738744-b1c5eb80-3e98-11e9-9786-29824935c9c2.png)

I tried to solve this issue by three ways, but both of them didn't get required result.

**First way: using of ArrayInput component of RA**
```
<SimpleForm>
      <ArrayInput source="signatures">
              <SimpleFormIterator>
                        { my fields }
               </SimpleFormIterator>
       </ArrayInput>
       { other fields }
</SimpleForm>

```
![image](https://user-images.githubusercontent.com/39263134/53739259-00c05080-3e9a-11e9-9cb8-c77b5a3735a7.png)

**Disadvantages:**
1) We should fill all items and save them, instead of principle fill -> add -> fill -> add -> etc.
2) I didn't find a way how to customize Add and Remove buttons
______________________________________________________________________________

**Second way: do it manually**

```
class Section extends Component {

state = {
    currentRow: null,
    rowsArray: []
}

// Update current value
changeValue = e => {
    this.setState({state => {
          const { currentRow } = state;
          const updateCurrentRow = Object.assign({}, currentRow, {[e.target.name]: e.target.value});
          return (
                currentRow: updateCurrentRow,
          );
    }})
}

// Save row
saveRow = () => {
     this.setState({state => {
          const { currentRow, rowsArray } = state;
          const updateRowsArray = rowsArray.concat(currentRow);
          return (
                rowsArray: updateRowsArray,
          );
    }})
}

   render() {
       return (
             ....... 
             <TableWithRows />
              <SimpleForm>
                       <TextField source="myField1" onChange={e => this.changeValue(e)}
                       <TextField source="myField2" onChange={e => this.changeValue(e)}
                       <AddNewButton onClick={() => this.saveRow()} />
                       { other fields }
               </SimpleForm>
              .........
        );
    }
}
```
Disadvantages:
1) I can't clean form after AddNewButton clicking
2) I should use two additional functions and save data in state
_______________________________________________________________________________

Third way: Create two forms. First one - only to save data to row. Second - to run action and save all data in store.

```
class Section extends Component {

   state = {
       rowsArray: []
   }

   // Save row
   saveRow = data => {
        this.setState({state => {
             const { rowsArray } = state;
             const updateRowsArray = rowsArray.concat(data);
             return (
                   rowsArray: updateRowsArray,
             );
        }})
    }

   // Run action and save all form info:
   runAction = data => {
         data.rowsArray = this.state.rowsArray; // Add my rows to form data
         this.props.saveDataToStore(data);
   }

  render() {
       return (
             ....... 
             <TableWithRows />
              <SimpleForm save={e => this.saveRow(e)} toolbar={<AddNewButton />}>
                       <TextField source="myField1" onChange={e => this.changeValue(e)}
                       <TextField source="myField2" onChange={e => this.changeValue(e)}                      
              </SimpleForm>
              <SimpleForm  save={e => this.runAction(e)}>
                       { other fields }
               </SimpleForm>
              .........
        );
    }
}
```
Disadvantages:
1) I can't clean form after AddNewButton clicking
_________________________________________________________________________________

So, I tried to solve this issue by three ways and all three results aren't suit...
Could you please give me an advice about this issue?

**Comment by fzaninotto** [comment]
I think the UI differs significantly with what ArrayInput offers, so I'd advise against solution 1.

In solutions 2 and 3, I don't know what a Section is, I don't know what TableWithRows is, so I can't tell you what's wrong with this snippet. Besides, instead of "addRow" or "changeValue", I advise you to name functions based on the domain (e.g. addSignature, saveSignature), that would make your code comprehensible.

What I see is that you're using SimpleForm and TextFields within a Section component, and it doesn't seem to be an Edit component. SimpleForm is designed to be used inside an edit component, and to handle changes on its own. If that's not your case, don't use it. Using onChange on Field components isn't supported. Instead, manage the form values by hand or using redux or redux-form directly.

So you're down to a pure react component for your use case. Why don't you reuse the one from the previous version of PulseTile?

**Comment by BogdanScherban** [comment]
@fzaninotto 
Thanks, Francois. 

About Sections. This plugin consists of 10 sections. Each section has a form. Please, look at this video: https://drive.google.com/file/d/1d6y7McITdp16Dl2KvLWi8K4SD2EvD4cT/view?usp=sharing

For each section I created template:
https://github.com/PulseTile/PulseTile-RA/blob/scotland/src/version/pages/ReSPECT/fragments/MainFormBlock.js

The children for this template is **SimpleForm** with **TextInputs** like:
https://github.com/PulseTile/PulseTile-RA/blob/scotland/src/version/pages/ReSPECT/sections/PersonalDetails.js

If I understand you correctly we should:
1) create custom component for Form (instead of **SimpleForm**) and use Material-UI **TextInput** instead of RA?
2) use this custom form component for this issue.

**Comment by fzaninotto** [comment]
Exactly. SimpleForm does some decoration and has its own onSave. If you handle save yourself, just use redux-form or plain React.

**Comment by BogdanScherban** [comment]
This issue has been done.
