### ISSUE TITLE
PulseTile expand button bugs

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile-RA#67]
- [ ] Add expand button for Problems / Issues
- [ ] Add expand button for Medications
- [ ] Add expand button for Vaccinations
- [ ] Add expand button for Contacts
- [ ] Add expand button for Allergies
- [ ] Add expand button for Top3Things

**Comment by BogdanScherban** [comment]
This issue has been done:expand button are presented at all pages
