### ISSUE TITLE
TextInput Cursor issue

### ISSUE THREAD

**Issue by BogdanScherban** [PulseTile/PulseTile-RA#72]
@fzaninotto 
Francois, could you please help with this issue?

Problem description

User want to edit information in Edit form. User install cursor in the middle of TextInput.
Cursor automatically moved to the end of input field after first letter was added.

Please, look at the video:
https://screencast-o-matic.com/watch/cqffDcZh8E

**Comment by PhilBarrett** [comment]
@BogdanScherban can you provide an update here please?

**Comment by BogdanScherban** [comment]
@PhilBarrett 
Phil, we need in Francois advice about this issue

**Comment by fzaninotto** [comment]
what kind of input is it? `<TextInput>`? `<RichTextInput>`?

**Comment by BogdanScherban** [comment]
@fzaninotto 
It is `<TextInput>` of React-admin

**Comment by fzaninotto** [comment]
I cannot reproduce this bug on react-admin, and I cannot find the code associated with your screencast. Can you point me to the code in this repository (and by the way, can you do that every time you ask for my help, because your issue doesn't have enough details for me to help you right away)?

**Comment by PhilBarrett** [comment]
Other implementations need to be updated for NES, One London and Showcase-RA

**Comment by BogdanScherban** [comment]
This issue was fixed. The reason was in re-rendering of theme after adding each new symbol to the input field. 

Solution:
```
import memoize from "lodash/memoize";

const theme = {....};

export default memoize(theme);
```

Earlier we used (it was the reason of error):
```
const theme = {....};

export default theme;
```

**Comment by PhilBarrett** [comment]
Reviewed and working fine now, thank you
