### ISSUE TITLE
Add Plugin Transfers of Care

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-RA#79]
In Showcase we have plugin Transfers of Care. We should move it to showcase-devra.

Approx. estimate time: 6-8h

**Comment by kuvakina** [comment]
Related issues:
#24 - Add Plugins (Simple)  - DONE
#25 - Add Plugin Event
#26 - Add Plugin Vitals - News
#27 - Add Plugin Images
#75 - Add Plugin Drawings
#76 - Add Plugin Documents
#77 - Add Plugin Clinical Statements
#78 - Add Plugin Orders
#80 - Add Plugin Test Results

**Comment by PhilBarrett** [comment]
Duplicate of https://github.com/RippleOSI/Ripple-Showcase-Stack-Project/issues/20 , closing here
