### ISSUE TITLE
Tour button issue on MPV

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-RA#83]
By clicking on Tour button from MPV (for Scotland(NES) and OneLondon projects) we are forwarded to Single page view.

Suggestion: hide Tour button form all pages except for Single page view.

**Comment by PhilBarrett** [comment]
Tour no longer on NES. Removing label

**Comment by kuvakina** [comment]
NES doesn't have Tour btn already: https://www.screencast.com/t/FPxOlNRsSvy

**Comment by kuvakina** [comment]
We hid Tour fo OneLondon:
![333333333333333333.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/66098e6e-d676-4a96-9040-d24e6e136f62)
![333333333333333333333333333.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/ed342f89-adea-4d0f-9ce3-a0d9b5b799c2)
